spring:
  application:
    name: chatEAT

  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000 #1시간
  
  refresh:
    expiration: 1209600000 #2주


logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

      hibernate:
        SQL: debug
